//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace revashare_svc_webapi.Client.RevaShareServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RevaShareServiceReference.IRevaShareDataService")]
    public interface IRevaShareDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevaShareDataService/passRide", ReplyAction="http://tempuri.org/IRevaShareDataService/passRideResponse")]
        revashare_svc_webapi.Logic.RevaShareServiceReference.RideDAO passRide();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevaShareDataService/passRide", ReplyAction="http://tempuri.org/IRevaShareDataService/passRideResponse")]
        System.Threading.Tasks.Task<revashare_svc_webapi.Logic.RevaShareServiceReference.RideDAO> passRideAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevaShareDataService/passUser", ReplyAction="http://tempuri.org/IRevaShareDataService/passUserResponse")]
        revashare_svc_webapi.Logic.RevaShareServiceReference.UserDAO passUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevaShareDataService/passUser", ReplyAction="http://tempuri.org/IRevaShareDataService/passUserResponse")]
        System.Threading.Tasks.Task<revashare_svc_webapi.Logic.RevaShareServiceReference.UserDAO> passUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevaShareDataService/passRideRider", ReplyAction="http://tempuri.org/IRevaShareDataService/passRideRiderResponse")]
        revashare_svc_webapi.Logic.RevaShareServiceReference.RideRidersDAO passRideRider();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRevaShareDataService/passRideRider", ReplyAction="http://tempuri.org/IRevaShareDataService/passRideRiderResponse")]
        System.Threading.Tasks.Task<revashare_svc_webapi.Logic.RevaShareServiceReference.RideRidersDAO> passRideRiderAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRevaShareDataServiceChannel : revashare_svc_webapi.Client.RevaShareServiceReference.IRevaShareDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RevaShareDataServiceClient : System.ServiceModel.ClientBase<revashare_svc_webapi.Client.RevaShareServiceReference.IRevaShareDataService>, revashare_svc_webapi.Client.RevaShareServiceReference.IRevaShareDataService {
        
        public RevaShareDataServiceClient() {
        }
        
        public RevaShareDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RevaShareDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RevaShareDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RevaShareDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public revashare_svc_webapi.Logic.RevaShareServiceReference.RideDAO passRide() {
            return base.Channel.passRide();
        }
        
        public System.Threading.Tasks.Task<revashare_svc_webapi.Logic.RevaShareServiceReference.RideDAO> passRideAsync() {
            return base.Channel.passRideAsync();
        }
        
        public revashare_svc_webapi.Logic.RevaShareServiceReference.UserDAO passUser() {
            return base.Channel.passUser();
        }
        
        public System.Threading.Tasks.Task<revashare_svc_webapi.Logic.RevaShareServiceReference.UserDAO> passUserAsync() {
            return base.Channel.passUserAsync();
        }
        
        public revashare_svc_webapi.Logic.RevaShareServiceReference.RideRidersDAO passRideRider() {
            return base.Channel.passRideRider();
        }
        
        public System.Threading.Tasks.Task<revashare_svc_webapi.Logic.RevaShareServiceReference.RideRidersDAO> passRideRiderAsync() {
            return base.Channel.passRideRiderAsync();
        }
    }
}
